name: Build Zed for Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Rust and wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build Zed
        run: cargo build --release

      - name: Run tests
        run: cargo test --workspace
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Zed Executable
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/zed.exe
          asset_name: zed.exe
          asset_content_type: application/vnd.microsoft.portable-executable
